POST http://localhost:3000/users
Content-Type: application/json

{
    "name":"Maria",
    "email":"maria@gmail.com",
    "password":"12345678920",
    "confirm_password": "12345678920"
}
###
POST http://localhost:3000/lists
Content-Type: application/json

{
  "userId": 1,
  "nombre": "Favoritas",
  "descripcion": "Las mejores pelis",
  "visibilidad": "public"
}

###
POST http://localhost:3000/lists/1/movies
Content-Type: application/json

{
  "tmdbId": 550,
  "titulo": "Fight Club",
  "poster_path": "/a26cQPRhJPX6GbWfQbvZdrrp9j9.jpg"
}